“在你开始理解需求时，尤其在需求来自于不同的利益相关者时，你就开始建立一些抽象概念，并建立一个词汇表。你展示业务过程的模型，与利益相关者一起发现工作的本质，得到清晰和可测量的需求，并将所有这些事实反馈给利益相关者。在做这些事情时，你就会改变（改进）他们对业务问题的看法。”

* 什么是需求
“需求就是产品支持其拥有者的业务所必须完成的事，或让拥有者接受并感兴趣所必须具备的品质”


* 需求的本质

1. 建立抽象概念并建立词汇表
2. 需求必须是准确的可度量、可测试的，如果可以用数字代替文字来测量需求，就能让需求可测试。如果你不能为需求找到测量指标，那它就不是需求，只是一种无根据的想法。
3. 即使完美的程序检验工作，也只能建立满足规格说明的程序。软件任务最难的部分在于，得到完整而一致的规格说明书。构建一个程序的许多本质工作，实际上就是消除规格说明书中的缺陷。
4. “如果人们对需求的含义有了更好的理解，他们就可能看到改进的办法。你的一部分工作就是帮助人们尽早理解和质疑他们的需求，这样他们就可以帮助你发现他们真正的需求。”

* 功能需求

“功能需求描述了一个动作，产品要对操作者有用，就必须执行该动作。功能需求源于利益相关者需要完成的工作。”

“功能需求是产品必须完成的那些事。”

* 非功能需求

“非功能需求是产品的属性或品质。”
“非功能需求描述了诸如观感、可用性、安全性和法律限制等需求，”

* 限制条件
“限制条件是全局性的需求。它们可以是对项目本身的限制，或是对产品最终设计的限制。”“限制条件是一个全局问题，约束着所有的需求。”“不论限制了什么，限制条件都可以看成是另一种类型的需求”

* Volere需求过程
需求过程的“目的是成功地收集、验证需求，并编写需求文档”

** 构建系统的方式：

*** 用户定制

*** 组件集成


** 项目启动
启动会议由利益相关者参与，主要包括：客户、关键用户、首席需求分析师、技术专家和业务专家。
启动会议确定了业务问题的范围，确认了需求发现工作中包含的重要功能、以及明确排除在外的功能。
“确定业务问题的范围通常是最方便的启动方式。”

“首席需求分析师协调整个小组的讨论，直到他们对工作的范围（也就是要研究的业务领域）以及工作与周围的世界有怎样的联系达成一致意见。会议参与“者们在白板上画出上下文范围模型图，展示工作所包含的功能，并引申开来，”
“上下文范围图建立了工作的范围，对确定许多风险承担者是有帮助的。”

“项目启动也确认了项目的目标。”
“在这个阶段对项目的需求部分所涉及的成本进行初步预估，是不错的项目管理实践。这可以通过工作范围模型中包含的信息来完成。对项目可能面临的风险进行早期评估，”

“最后，小组成员对项目是否值得进行和是否可行达成一致意见。这是“进行或终止”的决定。”

“或者，如果此时还有许多未知的东西，启动小组可以决定开始需求调研，不久后再来复查需求，重新评估项目的价值。”

** 网罗需求
启动会议结束后，需求分析师们将工作上下文图划分为业务用例。确定多少功能需要系统来实现，然后编写需求


“启动会议确定了待改进工作的范围。业务用例可以通过这个范围图导出。每个业务用例都由需求分析师和相关的利益相关者进行研究，以发现期望的工作方式。在理解了这些之后，就可以确定适合的产品（PUC场景），并写下需求或用户故事”


